subplot(2,2,1)
imagesc(img)
subtitle('Original Image')
subplot(2,2,2)
imagesc(img_ori_bessel)
subtitle('Original Image in FB basis')
subplot(2,2,3)
imagesc(img_recon)
subtitle('Reconstruction Image')
subplot(2,2,4)
imagesc(img_recon_r)
subtitle('Reconstruction Image with a rotation')