function output = Gaussian_Mixture(Centers_X,Centers_Y)
    % return a Gaussian mixture function generated by centers (Centers_X,Centers_Y)
    output = @(x,y) sum(exp(-pi*((Centers_X-x).^2+(Centers_Y-y).^2)));
end